name: E2E - Playwright

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  e2e-seeded:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d testdb" 
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && break || sleep 1
          done
        env:
          PGPASSWORD: postgres

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/testdb?schema=public" >> $GITHUB_ENV

      - name: Run Prisma deploy (db push)
        run: npx prisma db push --accept-data-loss

      - name: Run deterministic seed
        run: |
          # Run npm script if present, otherwise run the seed file directly with tsx.
          if npm run -s seed:places --silent; then
            echo "ran npm seed:places"
          else
            echo "npm script seed:places missing or failed; running seed file directly"
            npx tsx prisma/seed-places.ts
          fi

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js app
        run: |
          NODE_ENV=production npm run start &
          for i in {1..30}; do
            if curl -sS http://localhost:3000 > /dev/null; then
              echo "server ready"; break
            fi
            sleep 1
          done

      - name: Run Playwright tests against seeded DB
        run: npx playwright test --reporter=list --reporter=html --reporter=junit

      - name: Generate Playwright report (show-report)
        run: npx playwright show-report || true

      - name: Upload Playwright artifacts (seeded)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-seeded-report
          path: |
            playwright-report/**
            test-results/**
            playwright-debug-search.png
            playwright-search.png
            playwright-server-fetch.html
            playwright-debug-search.html
            playwright-api-fail.json
  # end of e2e-seeded
