name: E2E - Playwright

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for Playwright tests
        id: check
        run: |
          if [ -f playwright.config.ts ] || [ -f playwright.config.js ] || [ -d tests/e2e ] || ls tests/playwright* >/dev/null 2>&1; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip if no Playwright tests
        if: steps.check.outputs.has_tests == 'false'
        run: |
          echo "No Playwright config or e2e tests detected — skipping E2E job."

      - name: Install Playwright browsers
        if: steps.check.outputs.has_tests == 'true'
        run: npx playwright install --with-deps

      - name: Build Next.js app
        if: steps.check.outputs.has_tests == 'true'
        run: npm run build

      - name: Start Next.js app
        if: steps.check.outputs.has_tests == 'true'
        run: |
          npm run start &
          # wait for server to be ready
          for i in {1..30}; do
            if curl -sS http://localhost:3000 > /dev/null; then
              echo "server ready"; break
            fi
            sleep 1
          done
        env:
          NODE_ENV: production

      - name: Run Playwright tests
        if: steps.check.outputs.has_tests == 'true'
        run: |
          # ensure Playwright generates html report + junit results and traces when available
          npx playwright test --reporter=list --reporter=html --reporter=junit

      - name: Generate Playwright report (show-report)
        if: steps.check.outputs.has_tests == 'true'
        run: |
          # create the playwright-report directory even if tests passed without retries
          npx playwright show-report --output=playwright-report || true

      - name: List Playwright output directory (debug)
        if: steps.check.outputs.has_tests == 'true'
        run: |
          echo "=== ls -la playwright-report ==="
          ls -la playwright-report || true
          echo "=== ls -la test-results ==="
          ls -la test-results || true
          echo "=== ls -la . ==="
          ls -la . | sed -n '1,200p' || true

      - name: Upload Playwright traces
        if: always() && steps.check.outputs.has_tests == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: |
            playwright-report/**/trace.zip
            playwright-report/**/trace-*.zip
            test-results/**
            playwright-report/**

      - name: Upload Playwright report
        if: always() && steps.check.outputs.has_tests == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report
            playwright-debug-search.png
            playwright-search.png
            playwright-server-fetch.html
            playwright-debug-search.html
            playwright-api-fail.json
