name: E2E - Playwright

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - name: "Early: Save recursive listing"
        if: always()
        run: |
          mkdir -p ci-debug
          ls -laR . > ci-debug/recursive-ls.txt || true

      - name: "Early: Upload debug listing"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug
          path: ci-debug/recursive-ls.txt
          if-no-files-found: warn

      - name: Detect Playwright
        id: check
        run: |
          if [ -f playwright.config.ts ] || [ -f playwright.config.js ] || [ -d tests/e2e ] || ls tests/playwright* >/dev/null 2>&1; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Playwright browsers
        if: steps.check.outputs.has_tests == 'true'
        run: npx playwright install --with-deps

      - name: Build and start app
        if: steps.check.outputs.has_tests == 'true'
        run: |
          npm run build
          npm run start &
          for i in {1..30}; do
            if curl -sS http://localhost:3000 > /dev/null; then
              echo "server ready"; break
            fi
            sleep 1
          done
        env:
          NODE_ENV: production

      - name: Run Playwright tests
        if: steps.check.outputs.has_tests == 'true'
        run: npx playwright test --reporter=list,html,junit --workers=2 --trace on || true

      - name: Save recursive listing
        if: always()
        run: |
          mkdir -p ci-debug
          ls -laR . > ci-debug/recursive-ls.txt || true

      - name: Print head of listing
        if: always()
        run: head -n 200 ci-debug/recursive-ls.txt || true

      - name: "Debug: list playwright-report and test-results"
        if: always()
        run: |
          echo '--- listing playwright-report root ---'
          ls -la playwright-report || true
          echo '--- listing playwright-report/**/trace.zip (glob) ---'
          ls -la playwright-report/**/trace.zip || true
          echo '--- listing test-results ---'
          ls -la test-results || true

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: playwright-report/**/trace.zip
          if-no-files-found: warn

      - name: Upload debug listing
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug
          path: ci-debug/recursive-ls.txt
          if-no-files-found: warn

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report/**/trace.zip
            playwright-report
            test-results/**
          if-no-files-found: warn
