name: Manual E2E Runner

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout and run E2E against'
        required: true
        default: 'feature/PESC-008-search'

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout specified ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/testdb?schema=public" >> $GITHUB_ENV

      - name: Start Postgres service (ephemeral)
        uses: Harmon758/postgresql-action@v2
        with:
          postgresql version: '15'
          postgresql db: testdb
          postgresql user: postgres
          postgresql password: postgres

      - name: Run Prisma deploy (db push)
        run: npx prisma db push --accept-data-loss

      - name: Run deterministic seed
        run: |
          set -euo pipefail
          if npm run -s --if-present seed:places; then
            echo "npm seed ran"
          else
            npx tsx prisma/seed-places.ts
          fi

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Next.js app
        run: |
          npm run build

      - name: Start Next.js app
        run: |
          NODE_ENV=production npm run start &
          for i in {1..30}; do
            if curl -sS http://localhost:3000 > /dev/null; then
              echo "server ready"; break
            fi
            sleep 1
          done

      - name: Run Playwright tests
        run: npx playwright test --reporter=list --reporter=html --reporter=junit

      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        with:
          name: manual-playwright-report
          path: |
            playwright-report/**
            test-results/**
